dist: xenial
compiler: clang
language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5
matrix:
  include:
    - os: osx
      osx_image: xcode12
    - os: osx
      osx_image: xcode11.3
    - os: osx
      osx_image: xcode10.1
addons:
  apt:
    packages:
      - clang
      - pkg-config
bundler_args: --jobs=4 --retry=3
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then gem update bundler; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then gem update --system; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" -a "$TRAVIS_RUBY_VERSION" == "system" ]; then sudo gem install bundler; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" -a "$TRAVIS_RUBY_VERSION" != "system" ]; then gem update --system; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" -a "$TRAVIS_RUBY_VERSION" != "system" ]; then gem update bundler; fi
script:
  - git submodule update --init
  - bundle exec rake spec binary osx_varients --trace
deploy:
  provider: releases
  file_glob: true
  file: pkg/*.gem
  api_key:
    secure: OMCBceg89uRnU+FIPAPbeOK2pISvV4Cz62r9iTRIGXQCOOXX8M40i77/3DmtkMtc9FEuNyAu1+CH886PL2WtZZPK4CmEU3HuqXz1a5VsCI+zcAZL1tevKvblXOVQ3MG+B/SZRC3rEzGwjk4027WtzCCGoGCLUu4TFJP05+/8XN4=
  skip_cleanup: true
  on:
    tags: true
    rvm: '2.7' # Only deploy 1 of each platform
cache:
  bundler: true
notifications:
  recipients:
    - cowboyd@thefrontside.net
    - bordjukov@gmail.com
    - nightpool@cybre.space
